import type { Exercise } from "@/lib/types/domain";

/**
 * Fallback library used until a Supabase project is connected (see
 * src/services/movements/getExercises.ts). Mirrors the seed data in
 * supabase/seed.sql + supabase/seed_library.sql so local/demo mode and a
 * live project agree on both the original 4 movements and the full
 * exercise library.
 */
export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "push-ups",
    name: "Push-ups",
    category: "push",
    description:
      "Hands under shoulders, lower chest to just above the floor, press back up keeping your body in a straight line.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Start in a high plank: hands under shoulders, feet together, body in a straight line from head to heels.\n2. Brace your core and lower your chest toward the floor, elbows at roughly 45 degrees from your body.\n3. Stop just above the floor, then press back up to full arm extension without letting your hips sag or pike.",
    easierVariation:
      "Do them with your hands on a bench or step, or drop to your knees - same shape, less bodyweight to press.",
    harderVariation: "Elevate your feet on a bench, add a weighted vest, or slow the lowering phase to 3-4 seconds.",
  },
  {
    id: "pull-ups",
    name: "Pull-ups",
    category: "pull",
    description: "Dead hang from the bar, pull your chin above the bar, lower back down under control.",
    defaultReps: 4,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Grip the bar slightly wider than shoulder-width, palms facing away from you.\n2. Hang with arms fully extended and shoulder blades engaged (not fully relaxed/dead hang for the first rep).\n3. Pull your chin above the bar by driving your elbows down toward your hips.\n4. Lower back down under control to a full hang.",
    easierVariation:
      "Use a resistance band looped over the bar for assistance, or do slow negatives (jump to the top, lower for 4-5 seconds).",
    harderVariation: "Add a weighted vest or dip belt, or slow both the pull and the lower for tempo pull-ups.",
  },
  {
    id: "squats",
    name: "Squats",
    category: "legs",
    description:
      "Feet shoulder-width apart, hips back and down until thighs are at least parallel, drive back up through your heels.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet shoulder-width apart, toes slightly turned out.\n2. Push your hips back and bend your knees to lower down, keeping your chest up and heels planted.\n3. Go down until your thighs are at least parallel to the floor.\n4. Drive through your heels to stand back up.",
    easierVariation: "Squat to a bench or box behind you for a consistent depth cue, or reduce range of motion.",
    harderVariation:
      "Hold a weight at your chest (goblet-style), add a pause at the bottom, or try single-leg (pistol) squats.",
  },
  {
    id: "plank",
    name: "Plank (secs)",
    category: "core",
    description: "Forearms and toes on the floor, body in a straight line from head to heels, brace your core and hold.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Get into a forearm plank: elbows under shoulders, forearms flat on the floor.\n2. Extend your legs behind you, balancing on your toes, body in one straight line from head to heels.\n3. Brace your core and squeeze your glutes - don't let your hips sag or pike up.\n4. Hold, breathing steadily, for the target time.",
    easierVariation:
      "Drop to your knees while keeping the same straight line from head to knees, or shorten the hold time.",
    harderVariation:
      "Lift one foot off the ground at a time, or add a shoulder tap (alternating hands) to challenge stability.",
  },
  {
    id: "incline-push-ups",
    name: "Incline Push-ups",
    category: "push",
    description: "Push-up with hands elevated on a bench or step - an easier entry point into full push-ups.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Place your hands on a bench, step, or sturdy elevated surface, slightly wider than shoulder-width.\n2. Walk your feet back so your body forms a straight line from head to heels.\n3. Lower your chest toward the surface, then press back up to full extension.",
    easierVariation: "Use a higher surface (e.g. a wall or kitchen counter) to reduce the load further.",
    harderVariation: "Lower the incline (use a shorter step) until you're ready for push-ups from the floor.",
  },
  {
    id: "diamond-push-ups",
    name: "Diamond Push-ups",
    category: "push",
    description: "A close-grip push-up variation that shifts more emphasis onto the triceps.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Get into a push-up position with your hands together under your chest, thumbs and index fingers touching to form a diamond shape.\n2. Keep your elbows tucked close to your body as you lower your chest toward your hands.\n3. Press back up to full extension, keeping your core braced throughout.",
    easierVariation: "Drop to your knees, or widen your hand position slightly until your wrists and elbows feel comfortable.",
    harderVariation: "Elevate your feet on a bench, or add a slow 3-second lowering phase.",
  },
  {
    id: "pike-push-ups",
    name: "Pike Push-ups",
    category: "push",
    description:
      "A push-up variant done in a pike position that emphasizes the shoulders, a common stepping stone to handstand push-ups.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Start in a downward-dog-like position: hips high, hands and feet on the floor, forming an inverted V.\n2. Bend your elbows to lower the top of your head toward the floor between your hands.\n3. Press back up through your hands to return to the starting position.",
    easierVariation: "Elevate your hands on a step to reduce the angle, or reduce the range of motion.",
    harderVariation: "Elevate your feet on a bench to increase the angle toward vertical, working toward a handstand push-up.",
  },
  {
    id: "dips-parallel-bars",
    name: "Dips (Parallel Bars)",
    category: "push",
    description: "A compound pushing exercise on parallel bars or dip station that targets chest, shoulders, and triceps.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Grip parallel bars and support your body with arms extended, leaning slightly forward.\n2. Lower yourself by bending your elbows until your shoulders are about level with your elbows.\n3. Press back up to full arm extension without shrugging your shoulders toward your ears.",
    easierVariation: "Use an assisted-dip machine or a resistance band looped under your feet/knees for support.",
    harderVariation: "Add a weighted vest or dip belt, or add a pause at the bottom of each rep.",
  },
  {
    id: "bench-press-barbell",
    name: "Bench Press (Barbell)",
    category: "push",
    description: "The classic barbell chest press performed lying on a flat bench.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on a flat bench with your eyes under the bar, feet flat on the floor.\n2. Grip the bar slightly wider than shoulder-width and unrack it over your chest.\n3. Lower the bar under control to your mid-chest, elbows at roughly 45 degrees.\n4. Press the bar back up to full arm extension.",
    easierVariation: "Use lighter weight or dumbbells, which allow a more natural, forgiving path.",
    harderVariation: "Add a pause at the chest, slow the lowering tempo, or increase the load.",
  },
  {
    id: "overhead-press-dumbbell",
    name: "Overhead Press (Dumbbell)",
    category: "push",
    description: "A standing or seated press that builds shoulder strength and overhead stability.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand or sit holding a dumbbell in each hand at shoulder height, palms facing forward.\n2. Brace your core and press both dumbbells straight overhead until your arms are fully extended.\n3. Lower back down under control to shoulder height.",
    easierVariation: "Press one arm at a time, or use lighter dumbbells and a seated position for more stability.",
    harderVariation: "Press both dumbbells together for a strict standing press, or slow the lowering phase.",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "push",
    description: "A pressing movement on an inclined bench that emphasizes the upper chest.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a bench to a 30-45 degree incline and lie back with a dumbbell in each hand at shoulder height.\n2. Press the dumbbells up and slightly together until your arms are extended.\n3. Lower back down under control to the starting position.",
    easierVariation: "Use lighter dumbbells or reduce the incline angle closer to flat.",
    harderVariation: "Increase the weight, add a pause at the bottom, or slow the eccentric (lowering) phase.",
  },
  {
    id: "chin-ups",
    name: "Chin-ups",
    category: "pull",
    description: "A pull-up variation with an underhand grip that emphasizes the biceps more than a standard pull-up.",
    defaultReps: 6,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Grip the bar with palms facing you, hands shoulder-width apart.\n2. Hang with arms fully extended.\n3. Pull yourself up until your chin clears the bar, leading with your chest.\n4. Lower back down under control to a full hang.",
    easierVariation: "Use a resistance band for assistance, or perform slow negatives from the top position.",
    harderVariation: "Add a weighted vest, or pause for 1-2 seconds at the top of each rep.",
  },
  {
    id: "inverted-rows",
    name: "Inverted Rows",
    category: "pull",
    description: "A horizontal pulling exercise using a bar or rings set at waist height - a great pull-up progression.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a bar in a rack (or use rings) at around waist height.\n2. Lie under the bar and grip it with hands shoulder-width apart, body straight, heels on the floor.\n3. Pull your chest up to the bar, squeezing your shoulder blades together.\n4. Lower back down under control to full arm extension.",
    easierVariation: "Raise the bar higher so your body is more upright, reducing the amount of bodyweight you pull.",
    harderVariation: "Lower the bar, elevate your feet on a bench, or add a weight plate on your chest.",
  },
  {
    id: "bent-over-row-barbell",
    name: "Bent-Over Row (Barbell)",
    category: "pull",
    description: "A compound hinge-and-pull movement that builds the back and rear shoulders.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, hinge at the hips until your torso is close to parallel with the floor, knees slightly bent.\n2. Grip the bar just outside your knees, back flat.\n3. Pull the bar up toward your lower ribs, squeezing your shoulder blades together.\n4. Lower it back down under control without rounding your back.",
    easierVariation: "Use lighter weight, or perform the row supported with your chest on an incline bench.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "pull",
    description: "A machine exercise that mimics a pull-up, letting you scale the resistance precisely.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit at the lat pulldown machine and grip the bar wider than shoulder-width.\n2. Lean back slightly and pull the bar down to your upper chest, driving your elbows down and back.\n3. Control the bar back up to full arm extension without letting your shoulders shrug up.",
    easierVariation: "Reduce the weight stack, or use a closer grip to make the pull more manageable.",
    harderVariation: "Increase the weight, slow the return phase, or switch to a single-arm attachment.",
  },
  {
    id: "deadlift-conventional",
    name: "Deadlift (Conventional)",
    category: "pull",
    description: "A foundational hip-hinge pulling movement that builds total-body strength.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, the bar over your mid-foot.\n2. Hinge down and grip the bar just outside your knees, back flat, chest up.\n3. Drive through your heels and stand up tall, keeping the bar close to your body throughout.\n4. Lower the bar back down by hinging at the hips first, then bending the knees.",
    easierVariation: "Start with lighter weight or a trap bar, and pull from blocks/a rack to reduce the range of motion.",
    harderVariation: "Increase the load, add a pause just off the floor, or slow the lowering phase.",
  },
  {
    id: "face-pulls-cable",
    name: "Face Pulls (Cable)",
    category: "pull",
    description: "A rear-delt and upper-back isolation move that supports shoulder health.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a cable with a rope attachment at upper-chest to head height.\n2. Grip the rope with both hands, palms facing in, and step back to create tension.\n3. Pull the rope toward your face, flaring your elbows out and squeezing your shoulder blades together.\n4. Return to the start under control.",
    easierVariation: "Use a lighter weight and focus purely on the squeeze at the back position.",
    harderVariation: "Increase the weight or add a brief pause at the fully-pulled position each rep.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "legs",
    description: "A squat variation holding a single weight at the chest - great for learning squat depth and posture.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Hold a dumbbell or kettlebell vertically against your chest with both hands.\n2. Stand with feet shoulder-width apart, toes slightly out.\n3. Squat down by pushing your hips back and bending your knees, keeping your chest up.\n4. Drive through your heels to return to standing.",
    easierVariation: "Use a lighter weight or no weight at all, and reduce depth if needed.",
    harderVariation: "Increase the weight, add a 2-second pause at the bottom, or slow the descent.",
  },
  {
    id: "back-squat-barbell",
    name: "Back Squat (Barbell)",
    category: "legs",
    description: "The classic barbell squat with the bar racked across the upper back.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set the bar in a rack at about shoulder height and position it across your upper back.\n2. Unrack the bar, step back, and stand with feet shoulder-width apart.\n3. Squat down by pushing your hips back and bending your knees until thighs are at least parallel.\n4. Drive through your heels to stand back up.",
    easierVariation: "Reduce the weight, squat to a box for a consistent depth cue, or use a goblet squat instead.",
    harderVariation: "Increase the load, add a pause at the bottom, or slow the descent for extra time under tension.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    description: "A single-leg squat with the rear foot elevated behind you - builds strength and balance evenly on each side.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Stand a couple of feet in front of a bench, and rest the top of one foot on it behind you.\n2. Lower your back knee toward the floor by bending your front leg, keeping your torso upright.\n3. Push through your front heel to return to standing.\n4. Complete all reps on one side before switching legs.",
    easierVariation: "Reduce the range of motion, or hold onto something for balance.",
    harderVariation: "Hold dumbbells at your sides, or elevate your front foot slightly too for more range.",
  },
  {
    id: "walking-lunges",
    name: "Walking Lunges",
    category: "legs",
    description: "A dynamic lunge pattern that builds single-leg strength and balance through a full stride.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand tall, then step forward with one leg into a long stride.\n2. Lower your back knee toward the floor, keeping your front knee over your ankle.\n3. Push off your front foot to bring your back leg forward into the next stride.\n4. Continue alternating legs for the set.",
    easierVariation: "Take shorter steps, or do stationary reverse lunges instead of walking forward.",
    harderVariation: "Hold a dumbbell in each hand, or add a pause at the bottom of each stride.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "legs",
    description: "A machine-based squat pattern that lets you load the legs safely with back support.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit in the leg press machine with your feet shoulder-width apart on the platform.\n2. Release the safety and lower the platform by bending your knees toward your chest.\n3. Press back up through your heels to extend your legs without locking your knees out hard.",
    easierVariation: "Reduce the weight and use a smaller range of motion.",
    harderVariation: "Increase the weight, slow the lowering phase, or try a single-leg press.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "legs",
    description: "A simple hip-extension exercise that builds glute strength and is easy on the lower back.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with knees bent, feet flat on the floor hip-width apart.\n2. Squeeze your glutes and lift your hips up until your body forms a straight line from shoulders to knees.\n3. Lower back down under control without fully resting between reps.",
    easierVariation: "Reduce the range of motion, or perform fewer reps with more rest.",
    harderVariation: "Elevate your shoulders on a bench (hip thrust style), or add a weight across your hips.",
  },
  {
    id: "calf-raises",
    name: "Calf Raises",
    category: "legs",
    description: "A simple, targeted exercise for the calf muscles, done standing on flat ground or a raised edge.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, holding onto something for balance if needed.\n2. Rise up onto the balls of your feet as high as you can.\n3. Lower back down under control to the starting position.",
    easierVariation: "Hold onto a wall or rail for balance, or do fewer reps.",
    harderVariation: "Stand on the edge of a step to add extra range of motion, or do them single-leg.",
  },
  {
    id: "step-ups",
    name: "Step-Ups",
    category: "legs",
    description: "A functional single-leg exercise stepping onto a bench or box.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand in front of a sturdy bench or box.\n2. Step up with one foot, driving through that heel to bring your whole body up onto the box.\n3. Step back down under control and repeat, then switch legs.",
    easierVariation: "Use a lower step, or hold a rail for balance.",
    harderVariation: "Use a higher box, hold dumbbells, or step up without letting the trailing foot assist.",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "core",
    description: "A lateral core hold that targets the obliques and builds hip stability.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your side with your elbow under your shoulder and legs stacked.\n2. Lift your hips off the floor so your body forms a straight line from head to feet.\n3. Hold, keeping your hips lifted and core braced, for the target time, then switch sides.",
    easierVariation: "Bend your knees and stack them for a shorter lever arm, or shorten the hold time.",
    harderVariation: "Lift your top leg while holding the position, or add a reach-through with your top arm.",
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    category: "core",
    description: "A gymnastics-style core hold that builds full-body tension and control.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      '1. Lie on your back and press your lower back flat into the floor.\n2. Lift your shoulders and legs off the ground, arms extended overhead, legs straight.\n3. Hold this "banana" shape, keeping your lower back pressed down, for the target time.',
    easierVariation: "Bend your knees and keep your arms at your sides for a shorter, easier hold.",
    harderVariation: "Straighten your legs further and lower them closer to the floor, or add a gentle rock.",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "core",
    description: "A challenging hanging core exercise that targets the lower abs and hip flexors.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Hang from a pull-up bar with arms fully extended.\n2. Keeping your legs straight (or knees bent for an easier version), raise them up until at least parallel to the floor.\n3. Lower back down under control without swinging.",
    easierVariation: "Bend your knees and raise them toward your chest instead of keeping legs straight.",
    harderVariation: "Raise your straight legs all the way to touch the bar, controlling the descent fully.",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    category: "core",
    description: "A rotational core exercise performed seated, targeting the obliques.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit on the floor with knees bent, leaning back slightly to engage your core.\n2. Lift your feet slightly off the floor for more challenge, or keep them down for stability.\n3. Rotate your torso to touch the floor on one side, then the other, keeping your chest up.",
    easierVariation: "Keep your feet on the floor and reduce the range of the twist.",
    harderVariation: "Hold a weight plate or dumbbell with both hands as you twist, or lift your feet off the floor.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    description: "A slow, controlled core exercise that teaches you to brace your midsection while your limbs move.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with arms reaching straight up and knees bent 90 degrees over your hips.\n2. Press your lower back into the floor and slowly extend one arm overhead and the opposite leg straight out.\n3. Return to the start and repeat on the other side, keeping your lower back flat throughout.",
    easierVariation: "Move only your legs (keep arms still), or reduce how far you extend your leg.",
    harderVariation: "Add a light weight in your hands, or slow the tempo further.",
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    category: "core",
    description: "A dynamic core exercise performed from a plank position that also raises your heart rate.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Start in a high plank position, hands under shoulders, body straight.\n2. Drive one knee toward your chest, then quickly switch legs.\n3. Keep your hips low and core braced as you continue alternating at a controlled or fast pace.",
    easierVariation: "Slow the pace down significantly, or perform them with your hands elevated on a bench.",
    harderVariation: "Increase the pace, or add a plank shoulder tap between reps.",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    category: "core",
    description: "An advanced core exercise using an ab wheel (or barbell) that builds serious anti-extension strength.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Kneel on the floor holding an ab wheel (or barbell) in front of you.\n2. Brace your core and roll the wheel forward, extending your body as far as you can control.\n3. Pull back to the starting position using your core, not your arms.",
    easierVariation: "Only roll out a short distance, gradually increasing range as you get stronger.",
    harderVariation: "Roll out from a standing position instead of kneeling, or extend further before pulling back.",
  },
];
