import type { Exercise } from "@/lib/types/domain";

/**
 * Fallback library used until a Supabase project is connected (see
 * src/services/movements/getExercises.ts). Mirrors the seed data in
 * supabase/seed.sql + supabase/seed_library.sql so local/demo mode and a
 * live project agree on both the original 4 movements and the full
 * exercise library.
 */
export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: "push-ups",
    name: "Push-ups",
    category: "push",
    description:
      "Hands under shoulders, lower chest to just above the floor, press back up keeping your body in a straight line.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Start in a high plank: hands under shoulders, feet together, body in a straight line from head to heels.\n2. Brace your core and lower your chest toward the floor, elbows at roughly 45 degrees from your body.\n3. Stop just above the floor, then press back up to full arm extension without letting your hips sag or pike.",
    easierVariation:
      "Do them with your hands on a bench or step, or drop to your knees - same shape, less bodyweight to press.",
    harderVariation: "Elevate your feet on a bench, add a weighted vest, or slow the lowering phase to 3-4 seconds.",
  },
  {
    id: "pull-ups",
    name: "Pull-ups",
    category: "pull",
    description: "Dead hang from the bar, pull your chin above the bar, lower back down under control.",
    defaultReps: 4,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Grip the bar slightly wider than shoulder-width, palms facing away from you.\n2. Hang with arms fully extended and shoulder blades engaged (not fully relaxed/dead hang for the first rep).\n3. Pull your chin above the bar by driving your elbows down toward your hips.\n4. Lower back down under control to a full hang.",
    easierVariation:
      "Use a resistance band looped over the bar for assistance, or do slow negatives (jump to the top, lower for 4-5 seconds).",
    harderVariation: "Add a weighted vest or dip belt, or slow both the pull and the lower for tempo pull-ups.",
  },
  {
    id: "squats",
    name: "Squats",
    category: "legs",
    description:
      "Feet shoulder-width apart, hips back and down until thighs are at least parallel, drive back up through your heels.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet shoulder-width apart, toes slightly turned out.\n2. Push your hips back and bend your knees to lower down, keeping your chest up and heels planted.\n3. Go down until your thighs are at least parallel to the floor.\n4. Drive through your heels to stand back up.",
    easierVariation: "Squat to a bench or box behind you for a consistent depth cue, or reduce range of motion.",
    harderVariation:
      "Hold a weight at your chest (goblet-style), add a pause at the bottom, or try single-leg (pistol) squats.",
  },
  {
    id: "plank",
    name: "Plank (secs)",
    category: "core",
    description: "Forearms and toes on the floor, body in a straight line from head to heels, brace your core and hold.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Get into a forearm plank: elbows under shoulders, forearms flat on the floor.\n2. Extend your legs behind you, balancing on your toes, body in one straight line from head to heels.\n3. Brace your core and squeeze your glutes - don't let your hips sag or pike up.\n4. Hold, breathing steadily, for the target time.",
    easierVariation:
      "Drop to your knees while keeping the same straight line from head to knees, or shorten the hold time.",
    harderVariation:
      "Lift one foot off the ground at a time, or add a shoulder tap (alternating hands) to challenge stability.",
  },
  {
    id: "incline-push-ups",
    name: "Incline Push-ups",
    category: "push",
    description: "Push-up with hands elevated on a bench or step - an easier entry point into full push-ups.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Place your hands on a bench, step, or sturdy elevated surface, slightly wider than shoulder-width.\n2. Walk your feet back so your body forms a straight line from head to heels.\n3. Lower your chest toward the surface, then press back up to full extension.",
    easierVariation: "Use a higher surface (e.g. a wall or kitchen counter) to reduce the load further.",
    harderVariation: "Lower the incline (use a shorter step) until you're ready for push-ups from the floor.",
  },
  {
    id: "diamond-push-ups",
    name: "Diamond Push-ups",
    category: "push",
    description: "A close-grip push-up variation that shifts more emphasis onto the triceps.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Get into a push-up position with your hands together under your chest, thumbs and index fingers touching to form a diamond shape.\n2. Keep your elbows tucked close to your body as you lower your chest toward your hands.\n3. Press back up to full extension, keeping your core braced throughout.",
    easierVariation: "Drop to your knees, or widen your hand position slightly until your wrists and elbows feel comfortable.",
    harderVariation: "Elevate your feet on a bench, or add a slow 3-second lowering phase.",
  },
  {
    id: "pike-push-ups",
    name: "Pike Push-ups",
    category: "push",
    description:
      "A push-up variant done in a pike position that emphasizes the shoulders, a common stepping stone to handstand push-ups.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Start in a downward-dog-like position: hips high, hands and feet on the floor, forming an inverted V.\n2. Bend your elbows to lower the top of your head toward the floor between your hands.\n3. Press back up through your hands to return to the starting position.",
    easierVariation: "Elevate your hands on a step to reduce the angle, or reduce the range of motion.",
    harderVariation: "Elevate your feet on a bench to increase the angle toward vertical, working toward a handstand push-up.",
  },
  {
    id: "dips-parallel-bars",
    name: "Dips (Parallel Bars)",
    category: "push",
    description: "A compound pushing exercise on parallel bars or dip station that targets chest, shoulders, and triceps.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Grip parallel bars and support your body with arms extended, leaning slightly forward.\n2. Lower yourself by bending your elbows until your shoulders are about level with your elbows.\n3. Press back up to full arm extension without shrugging your shoulders toward your ears.",
    easierVariation: "Use an assisted-dip machine or a resistance band looped under your feet/knees for support.",
    harderVariation: "Add a weighted vest or dip belt, or add a pause at the bottom of each rep.",
  },
  {
    id: "bench-press-barbell",
    name: "Bench Press (Barbell)",
    category: "push",
    description: "The classic barbell chest press performed lying on a flat bench.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on a flat bench with your eyes under the bar, feet flat on the floor.\n2. Grip the bar slightly wider than shoulder-width and unrack it over your chest.\n3. Lower the bar under control to your mid-chest, elbows at roughly 45 degrees.\n4. Press the bar back up to full arm extension.",
    easierVariation: "Use lighter weight or dumbbells, which allow a more natural, forgiving path.",
    harderVariation: "Add a pause at the chest, slow the lowering tempo, or increase the load.",
  },
  {
    id: "overhead-press-dumbbell",
    name: "Overhead Press (Dumbbell)",
    category: "push",
    description: "A standing or seated press that builds shoulder strength and overhead stability.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand or sit holding a dumbbell in each hand at shoulder height, palms facing forward.\n2. Brace your core and press both dumbbells straight overhead until your arms are fully extended.\n3. Lower back down under control to shoulder height.",
    easierVariation: "Press one arm at a time, or use lighter dumbbells and a seated position for more stability.",
    harderVariation: "Press both dumbbells together for a strict standing press, or slow the lowering phase.",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "push",
    description: "A pressing movement on an inclined bench that emphasizes the upper chest.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a bench to a 30-45 degree incline and lie back with a dumbbell in each hand at shoulder height.\n2. Press the dumbbells up and slightly together until your arms are extended.\n3. Lower back down under control to the starting position.",
    easierVariation: "Use lighter dumbbells or reduce the incline angle closer to flat.",
    harderVariation: "Increase the weight, add a pause at the bottom, or slow the eccentric (lowering) phase.",
  },
  {
    id: "chin-ups",
    name: "Chin-ups",
    category: "pull",
    description: "A pull-up variation with an underhand grip that emphasizes the biceps more than a standard pull-up.",
    defaultReps: 6,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Grip the bar with palms facing you, hands shoulder-width apart.\n2. Hang with arms fully extended.\n3. Pull yourself up until your chin clears the bar, leading with your chest.\n4. Lower back down under control to a full hang.",
    easierVariation: "Use a resistance band for assistance, or perform slow negatives from the top position.",
    harderVariation: "Add a weighted vest, or pause for 1-2 seconds at the top of each rep.",
  },
  {
    id: "inverted-rows",
    name: "Inverted Rows",
    category: "pull",
    description: "A horizontal pulling exercise using a bar or rings set at waist height - a great pull-up progression.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a bar in a rack (or use rings) at around waist height.\n2. Lie under the bar and grip it with hands shoulder-width apart, body straight, heels on the floor.\n3. Pull your chest up to the bar, squeezing your shoulder blades together.\n4. Lower back down under control to full arm extension.",
    easierVariation: "Raise the bar higher so your body is more upright, reducing the amount of bodyweight you pull.",
    harderVariation: "Lower the bar, elevate your feet on a bench, or add a weight plate on your chest.",
  },
  {
    id: "bent-over-row-barbell",
    name: "Bent-Over Row (Barbell)",
    category: "pull",
    description: "A compound hinge-and-pull movement that builds the back and rear shoulders.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, hinge at the hips until your torso is close to parallel with the floor, knees slightly bent.\n2. Grip the bar just outside your knees, back flat.\n3. Pull the bar up toward your lower ribs, squeezing your shoulder blades together.\n4. Lower it back down under control without rounding your back.",
    easierVariation: "Use lighter weight, or perform the row supported with your chest on an incline bench.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "pull",
    description: "A machine exercise that mimics a pull-up, letting you scale the resistance precisely.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit at the lat pulldown machine and grip the bar wider than shoulder-width.\n2. Lean back slightly and pull the bar down to your upper chest, driving your elbows down and back.\n3. Control the bar back up to full arm extension without letting your shoulders shrug up.",
    easierVariation: "Reduce the weight stack, or use a closer grip to make the pull more manageable.",
    harderVariation: "Increase the weight, slow the return phase, or switch to a single-arm attachment.",
  },
  {
    id: "deadlift-conventional",
    name: "Deadlift (Conventional)",
    category: "pull",
    description: "A foundational hip-hinge pulling movement that builds total-body strength.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, the bar over your mid-foot.\n2. Hinge down and grip the bar just outside your knees, back flat, chest up.\n3. Drive through your heels and stand up tall, keeping the bar close to your body throughout.\n4. Lower the bar back down by hinging at the hips first, then bending the knees.",
    easierVariation: "Start with lighter weight or a trap bar, and pull from blocks/a rack to reduce the range of motion.",
    harderVariation: "Increase the load, add a pause just off the floor, or slow the lowering phase.",
  },
  {
    id: "face-pulls-cable",
    name: "Face Pulls (Cable)",
    category: "pull",
    description: "A rear-delt and upper-back isolation move that supports shoulder health.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a cable with a rope attachment at upper-chest to head height.\n2. Grip the rope with both hands, palms facing in, and step back to create tension.\n3. Pull the rope toward your face, flaring your elbows out and squeezing your shoulder blades together.\n4. Return to the start under control.",
    easierVariation: "Use a lighter weight and focus purely on the squeeze at the back position.",
    harderVariation: "Increase the weight or add a brief pause at the fully-pulled position each rep.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "legs",
    description: "A squat variation holding a single weight at the chest - great for learning squat depth and posture.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Hold a dumbbell or kettlebell vertically against your chest with both hands.\n2. Stand with feet shoulder-width apart, toes slightly out.\n3. Squat down by pushing your hips back and bending your knees, keeping your chest up.\n4. Drive through your heels to return to standing.",
    easierVariation: "Use a lighter weight or no weight at all, and reduce depth if needed.",
    harderVariation: "Increase the weight, add a 2-second pause at the bottom, or slow the descent.",
  },
  {
    id: "back-squat-barbell",
    name: "Back Squat (Barbell)",
    category: "legs",
    description: "The classic barbell squat with the bar racked across the upper back.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set the bar in a rack at about shoulder height and position it across your upper back.\n2. Unrack the bar, step back, and stand with feet shoulder-width apart.\n3. Squat down by pushing your hips back and bending your knees until thighs are at least parallel.\n4. Drive through your heels to stand back up.",
    easierVariation: "Reduce the weight, squat to a box for a consistent depth cue, or use a goblet squat instead.",
    harderVariation: "Increase the load, add a pause at the bottom, or slow the descent for extra time under tension.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    description: "A single-leg squat with the rear foot elevated behind you - builds strength and balance evenly on each side.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Stand a couple of feet in front of a bench, and rest the top of one foot on it behind you.\n2. Lower your back knee toward the floor by bending your front leg, keeping your torso upright.\n3. Push through your front heel to return to standing.\n4. Complete all reps on one side before switching legs.",
    easierVariation: "Reduce the range of motion, or hold onto something for balance.",
    harderVariation: "Hold dumbbells at your sides, or elevate your front foot slightly too for more range.",
  },
  {
    id: "walking-lunges",
    name: "Walking Lunges",
    category: "legs",
    description: "A dynamic lunge pattern that builds single-leg strength and balance through a full stride.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand tall, then step forward with one leg into a long stride.\n2. Lower your back knee toward the floor, keeping your front knee over your ankle.\n3. Push off your front foot to bring your back leg forward into the next stride.\n4. Continue alternating legs for the set.",
    easierVariation: "Take shorter steps, or do stationary reverse lunges instead of walking forward.",
    harderVariation: "Hold a dumbbell in each hand, or add a pause at the bottom of each stride.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    category: "legs",
    description: "A machine-based squat pattern that lets you load the legs safely with back support.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit in the leg press machine with your feet shoulder-width apart on the platform.\n2. Release the safety and lower the platform by bending your knees toward your chest.\n3. Press back up through your heels to extend your legs without locking your knees out hard.",
    easierVariation: "Reduce the weight and use a smaller range of motion.",
    harderVariation: "Increase the weight, slow the lowering phase, or try a single-leg press.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "legs",
    description: "A simple hip-extension exercise that builds glute strength and is easy on the lower back.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with knees bent, feet flat on the floor hip-width apart.\n2. Squeeze your glutes and lift your hips up until your body forms a straight line from shoulders to knees.\n3. Lower back down under control without fully resting between reps.",
    easierVariation: "Reduce the range of motion, or perform fewer reps with more rest.",
    harderVariation: "Elevate your shoulders on a bench (hip thrust style), or add a weight across your hips.",
  },
  {
    id: "calf-raises",
    name: "Calf Raises",
    category: "legs",
    description: "A simple, targeted exercise for the calf muscles, done standing on flat ground or a raised edge.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet hip-width apart, holding onto something for balance if needed.\n2. Rise up onto the balls of your feet as high as you can.\n3. Lower back down under control to the starting position.",
    easierVariation: "Hold onto a wall or rail for balance, or do fewer reps.",
    harderVariation: "Stand on the edge of a step to add extra range of motion, or do them single-leg.",
  },
  {
    id: "step-ups",
    name: "Step-Ups",
    category: "legs",
    description: "A functional single-leg exercise stepping onto a bench or box.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand in front of a sturdy bench or box.\n2. Step up with one foot, driving through that heel to bring your whole body up onto the box.\n3. Step back down under control and repeat, then switch legs.",
    easierVariation: "Use a lower step, or hold a rail for balance.",
    harderVariation: "Use a higher box, hold dumbbells, or step up without letting the trailing foot assist.",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "core",
    description: "A lateral core hold that targets the obliques and builds hip stability.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your side with your elbow under your shoulder and legs stacked.\n2. Lift your hips off the floor so your body forms a straight line from head to feet.\n3. Hold, keeping your hips lifted and core braced, for the target time, then switch sides.",
    easierVariation: "Bend your knees and stack them for a shorter lever arm, or shorten the hold time.",
    harderVariation: "Lift your top leg while holding the position, or add a reach-through with your top arm.",
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    category: "core",
    description: "A gymnastics-style core hold that builds full-body tension and control.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      '1. Lie on your back and press your lower back flat into the floor.\n2. Lift your shoulders and legs off the ground, arms extended overhead, legs straight.\n3. Hold this "banana" shape, keeping your lower back pressed down, for the target time.',
    easierVariation: "Bend your knees and keep your arms at your sides for a shorter, easier hold.",
    harderVariation: "Straighten your legs further and lower them closer to the floor, or add a gentle rock.",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "core",
    description: "A challenging hanging core exercise that targets the lower abs and hip flexors.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Hang from a pull-up bar with arms fully extended.\n2. Keeping your legs straight (or knees bent for an easier version), raise them up until at least parallel to the floor.\n3. Lower back down under control without swinging.",
    easierVariation: "Bend your knees and raise them toward your chest instead of keeping legs straight.",
    harderVariation: "Raise your straight legs all the way to touch the bar, controlling the descent fully.",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    category: "core",
    description: "A rotational core exercise performed seated, targeting the obliques.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit on the floor with knees bent, leaning back slightly to engage your core.\n2. Lift your feet slightly off the floor for more challenge, or keep them down for stability.\n3. Rotate your torso to touch the floor on one side, then the other, keeping your chest up.",
    easierVariation: "Keep your feet on the floor and reduce the range of the twist.",
    harderVariation: "Hold a weight plate or dumbbell with both hands as you twist, or lift your feet off the floor.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    description: "A slow, controlled core exercise that teaches you to brace your midsection while your limbs move.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with arms reaching straight up and knees bent 90 degrees over your hips.\n2. Press your lower back into the floor and slowly extend one arm overhead and the opposite leg straight out.\n3. Return to the start and repeat on the other side, keeping your lower back flat throughout.",
    easierVariation: "Move only your legs (keep arms still), or reduce how far you extend your leg.",
    harderVariation: "Add a light weight in your hands, or slow the tempo further.",
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    category: "core",
    description: "A dynamic core exercise performed from a plank position that also raises your heart rate.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Start in a high plank position, hands under shoulders, body straight.\n2. Drive one knee toward your chest, then quickly switch legs.\n3. Keep your hips low and core braced as you continue alternating at a controlled or fast pace.",
    easierVariation: "Slow the pace down significantly, or perform them with your hands elevated on a bench.",
    harderVariation: "Increase the pace, or add a plank shoulder tap between reps.",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    category: "core",
    description: "An advanced core exercise using an ab wheel (or barbell) that builds serious anti-extension strength.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Kneel on the floor holding an ab wheel (or barbell) in front of you.\n2. Brace your core and roll the wheel forward, extending your body as far as you can control.\n3. Pull back to the starting position using your core, not your arms.",
    easierVariation: "Only roll out a short distance, gradually increasing range as you get stronger.",
    harderVariation: "Roll out from a standing position instead of kneeling, or extend further before pulling back.",
  },
  // --- Phase 4 additions: shoulders/arms/cardio categories + broader push/pull/legs/core coverage ---
  {
    id: "decline-bench-press",
    name: "Decline Bench Press",
    category: "push",
    description: "A barbell press on a decline bench that emphasizes the lower chest.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Set a bench to a slight decline and lock your feet under the pads.\n2. Grip the bar slightly wider than shoulder-width and unrack it over your lower chest.\n3. Lower the bar under control to your lower chest, then press back up to full extension.",
    easierVariation: "Use lighter weight or dumbbells for a more natural pressing path.",
    harderVariation: "Increase the load, add a pause at the chest, or slow the lowering tempo.",
  },
  {
    id: "dumbbell-chest-fly",
    name: "Dumbbell Chest Fly",
    category: "push",
    description: "An isolation move for the chest performed lying on a flat bench with a wide arcing motion.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on a flat bench holding a dumbbell in each hand above your chest, palms facing each other, elbows slightly bent.\n2. Lower the dumbbells out to the sides in a wide arc until you feel a stretch across your chest.\n3. Bring the dumbbells back together above your chest, squeezing your pecs at the top.",
    easierVariation: "Use lighter dumbbells and reduce the range of motion.",
    harderVariation: "Increase the weight, add a pause at the bottom stretch, or try it on an incline bench.",
  },
  {
    id: "cable-crossover",
    name: "Cable Crossover",
    category: "push",
    description: "A cable isolation exercise that keeps constant tension on the chest through a full range of motion.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Set both cable pulleys above head height and grip a handle in each hand.\n2. Step forward with a slight forward lean and a soft bend in your elbows.\n3. Bring your hands together in front of your hips in a wide arcing motion, squeezing your chest at the bottom.",
    easierVariation: "Use lighter weight and set the pulleys at chest height for a shorter range.",
    harderVariation: "Increase the weight, or set the pulleys lower and cross your hands over at the bottom.",
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    category: "push",
    description: "A bench press variation with hands closer together that shifts emphasis onto the triceps.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Lie on a flat bench and grip the bar with hands just inside shoulder-width.\n2. Unrack the bar and lower it under control to your lower chest, keeping your elbows tucked.\n3. Press back up to full extension, focusing on driving through your triceps.",
    easierVariation: "Use lighter weight or dumbbells held close together.",
    harderVariation: "Increase the load, add a pause at the chest, or slow the lowering phase.",
  },
  {
    id: "floor-press",
    name: "Floor Press",
    category: "push",
    description: "A pressing variation performed lying on the floor that limits range of motion and protects the shoulders.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on the floor with knees bent, feet flat, holding a barbell or dumbbells over your chest.\n2. Lower your upper arms until your elbows touch the floor, then pause briefly.\n3. Press back up to full extension without arching your lower back off the floor.",
    easierVariation: "Use lighter weight and focus on a controlled, pain-free range.",
    harderVariation: "Increase the load, add a 2-second pause at the bottom, or use a single arm at a time.",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    category: "push",
    description: "A guided pressing machine that lets you focus purely on the chest without balancing free weight.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Adjust the seat so the handles line up with your mid-chest.\n2. Press the handles forward to full arm extension without locking your elbows out hard.\n3. Return under control back to the starting position.",
    easierVariation: "Reduce the weight stack and use a partial range of motion.",
    harderVariation: "Increase the weight, slow the return phase, or press one arm at a time.",
  },
  {
    id: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    category: "pull",
    description: "A unilateral rowing exercise that lets you focus on each side of the back individually.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Place one knee and hand on a bench, keeping your back flat and parallel to the floor.\n2. Hold a dumbbell in your free hand, arm fully extended toward the floor.\n3. Pull the dumbbell up toward your hip, driving your elbow back and squeezing your shoulder blade.\n4. Lower back down under control, then complete all reps before switching sides.",
    easierVariation: "Use a lighter dumbbell or reduce the range of motion.",
    harderVariation: "Increase the weight, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    category: "pull",
    description: "A heavy compound row performed with a landmine or T-bar attachment.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Straddle the bar with a chest-supported or hinged torso position, knees slightly bent.\n2. Grip the handles and pull the weight up toward your chest, squeezing your shoulder blades together.\n3. Lower back down under control without rounding your back.",
    easierVariation: "Use lighter weight, or perform it chest-supported on an incline bench for stability.",
    harderVariation: "Increase the load, add a pause at the top, or slow the eccentric.",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    category: "pull",
    description: "A horizontal pulling exercise on a cable machine that builds mid-back thickness.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit at the cable row station with knees slightly bent, feet braced on the platform.\n2. Grip the handle and pull it toward your torso, keeping your back straight and elbows close to your body.\n3. Extend your arms back out under control without rounding your lower back.",
    easierVariation: "Reduce the weight stack and focus on a shorter, controlled range.",
    harderVariation: "Increase the weight, pause at full contraction, or slow the return.",
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    category: "pull",
    description: "A lat isolation exercise performed on a cable with straight arms.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Grip a straight bar or rope attached to a high cable, arms extended in front of you.\n2. Keeping your arms mostly straight, pull the bar down toward your thighs by engaging your lats.\n3. Let the bar return under control to the starting position.",
    easierVariation: "Use lighter weight and a smaller range of motion.",
    harderVariation: "Increase the weight, or add a brief pause at the bottom of each rep.",
  },
  {
    id: "barbell-shrugs",
    name: "Barbell Shrugs",
    category: "pull",
    description: "A simple isolation exercise for the trapezius muscles.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a barbell (or dumbbells) in front of your thighs, arms straight.\n2. Shrug your shoulders straight up toward your ears as high as you can.\n3. Lower back down under control without rolling your shoulders.",
    easierVariation: "Use lighter weight and focus on the squeeze at the top.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    category: "pull",
    description: "A hip-hinge exercise with a barbell across the back that strengthens the hamstrings and lower back.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Rest a barbell across your upper back like a squat, feet shoulder-width apart.\n2. Keeping a slight bend in your knees and back flat, hinge forward at the hips until your torso is close to parallel with the floor.\n3. Drive your hips forward to return to standing.",
    easierVariation: "Use light weight or no weight at all, and reduce the range of motion.",
    harderVariation: "Increase the load, or slow the forward hinge for extra time under tension.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    category: "legs",
    description: "A machine isolation exercise that targets the quadriceps directly.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit in the leg extension machine with the pad resting on the front of your lower shins.\n2. Extend your legs to straighten them fully, squeezing your quads at the top.\n3. Lower back down under control without letting the weight stack slam.",
    easierVariation: "Reduce the weight and use a smaller range of motion.",
    harderVariation: "Increase the weight, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    category: "legs",
    description: "A machine isolation exercise for the hamstrings.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit in the leg curl machine with the pad resting against the back of your lower legs.\n2. Curl your legs down and back by bending your knees, squeezing your hamstrings.\n3. Return to the starting position under control.",
    easierVariation: "Reduce the weight and use a smaller range of motion.",
    harderVariation: "Increase the weight, add a pause at full contraction, or slow the return.",
  },
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    category: "legs",
    description: "A glute-focused hip extension exercise performed with your shoulders resting on a bench.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit on the floor with your upper back against a bench, a barbell across your hips.\n2. Plant your feet flat, hip-width apart, close to your glutes.\n3. Drive through your heels to lift your hips up until your body forms a straight line from shoulders to knees.\n4. Lower back down under control without resting the bar on the floor between reps.",
    easierVariation: "Use no weight or light weight, and focus on the hip movement pattern.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    category: "legs",
    description: "A machine-based squat performed on an angled sled that heavily targets the quadriceps.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Position yourself in the hack squat machine with your shoulders and back against the pads.\n2. Lower yourself by bending your knees until your thighs are at least parallel to the platform.\n3. Drive through your heels to return to the starting position.",
    easierVariation: "Reduce the weight and limit the depth of the squat.",
    harderVariation: "Increase the weight, add a pause at the bottom, or slow the descent.",
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    category: "legs",
    description: "A wide-stance deadlift variation that shifts emphasis onto the inner thighs and glutes.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Stand with a wide stance, toes pointed out, the bar over your mid-foot.\n2. Grip the bar inside your knees with a flat back and chest up.\n3. Drive through your heels and stand up tall, keeping the bar close to your body.\n4. Lower the bar back down by hinging at the hips first.",
    easierVariation: "Use lighter weight or a trap bar, and narrow the stance slightly if it feels awkward.",
    harderVariation: "Increase the load, add a pause just off the floor, or slow the lowering phase.",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    description: "A hip-hinge movement performed with a slight knee bend that targets the hamstrings and glutes.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a barbell or dumbbells in front of your thighs, feet hip-width apart.\n2. With a slight bend in your knees, hinge at the hips and lower the weight down your legs, keeping your back flat.\n3. Feel a stretch in your hamstrings, then drive your hips forward to return to standing.",
    easierVariation: "Use lighter weight and stop the descent higher up, before you feel a strong stretch.",
    harderVariation: "Increase the load, add a pause at the bottom, or slow the lowering phase.",
  },
  {
    id: "front-squat",
    name: "Front Squat",
    category: "legs",
    description: "A squat variation with the bar racked across the front of your shoulders, emphasizing the quads and upper back.",
    defaultReps: 6,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Rack the bar across the front of your shoulders, elbows up, fingertips supporting the bar.\n2. Stand with feet shoulder-width apart and unrack the bar.\n3. Squat down keeping your torso upright until your thighs are at least parallel to the floor.\n4. Drive through your heels to stand back up.",
    easierVariation: "Use lighter weight, or hold the bar in a cross-arm grip if wrist mobility is limited.",
    harderVariation: "Increase the load, add a pause at the bottom, or slow the descent.",
  },
  {
    id: "pistol-squat",
    name: "Pistol Squat",
    category: "legs",
    description: "A demanding single-leg bodyweight squat that builds serious strength and balance.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Stand on one leg with the other leg extended straight out in front of you.\n2. Slowly lower yourself down by bending your standing knee, keeping the extended leg off the floor.\n3. Go as low as you can with control, then drive back up to standing.\n4. Complete all reps on one side before switching legs.",
    easierVariation: "Hold onto a doorframe or TRX straps for balance and assistance, or squat to a low box.",
    harderVariation: "Hold a weight at your chest, or slow the lowering phase further.",
  },
  {
    id: "overhead-press-barbell",
    name: "Overhead Press (Barbell)",
    category: "shoulders",
    description: "A standing barbell press that builds raw shoulder strength.",
    defaultReps: 6,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Grip the bar just outside shoulder-width and rest it on your front shoulders.\n2. Brace your core and press the bar straight overhead until your arms are fully extended.\n3. Lower back down under control to the starting position.",
    easierVariation: "Use lighter weight, or perform the press seated for more stability.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    category: "shoulders",
    description: "A dumbbell press variation with a rotating grip that works all three heads of the shoulder.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit or stand holding dumbbells in front of your shoulders, palms facing you.\n2. Press the dumbbells overhead while rotating your palms to face forward.\n3. Reverse the rotation as you lower back down to the starting position.",
    easierVariation: "Use lighter dumbbells and reduce the rotation range.",
    harderVariation: "Increase the weight, or slow both the press and the lowering phase.",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    category: "shoulders",
    description: "An isolation exercise for the side delts that builds shoulder width.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a dumbbell in each hand at your sides, a slight bend in your elbows.\n2. Raise both arms out to the sides until they reach shoulder height.\n3. Lower back down under control without swinging the weight.",
    easierVariation: "Use lighter dumbbells and a smaller range of motion.",
    harderVariation: "Increase the weight, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "front-raise",
    name: "Front Raise",
    category: "shoulders",
    description: "An isolation exercise that targets the front delts.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a dumbbell in each hand in front of your thighs.\n2. Raise one or both arms straight in front of you to shoulder height.\n3. Lower back down under control and repeat.",
    easierVariation: "Use lighter dumbbells or alternate arms instead of raising both together.",
    harderVariation: "Increase the weight, or hold at the top briefly each rep.",
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    category: "shoulders",
    description: "An isolation move for the rear delts and upper back that supports posture.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Hinge forward at the hips holding a dumbbell in each hand, arms hanging with a slight bend in the elbows.\n2. Raise both arms out to the sides, squeezing your shoulder blades together.\n3. Lower back down under control.",
    easierVariation: "Use lighter dumbbells and a smaller range of motion.",
    harderVariation: "Increase the weight, or add a pause at the top of each rep.",
  },
  {
    id: "upright-row",
    name: "Upright Row",
    category: "shoulders",
    description: "A vertical pulling exercise that targets the side delts and traps.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a barbell or dumbbells in front of your thighs, hands shoulder-width apart.\n2. Pull the weight straight up toward your chin, leading with your elbows.\n3. Lower back down under control to the starting position.",
    easierVariation: "Use lighter weight and stop the pull at chest height.",
    harderVariation: "Increase the weight, or add a pause at the top of each rep.",
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    category: "shoulders",
    description: "A guided pressing machine that isolates the shoulders without balance demands.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Adjust the seat so the handles line up with your shoulders.\n2. Press the handles straight up until your arms are extended without locking out hard.\n3. Return under control back to the starting position.",
    easierVariation: "Reduce the weight stack and use a partial range of motion.",
    harderVariation: "Increase the weight, slow the return phase, or press one arm at a time.",
  },
  {
    id: "handstand-push-up",
    name: "Handstand Push-up",
    category: "shoulders",
    description: "An advanced calisthenics press performed upside-down against a wall that builds serious shoulder strength.",
    defaultReps: 5,
    defaultSets: 3,
    difficultyTier: 3,
    instructions:
      "1. Kick up into a handstand against a wall, hands shoulder-width apart.\n2. Bend your elbows to slowly lower the top of your head toward the floor.\n3. Press back up through your hands to full arm extension.",
    easierVariation: "Work pike push-ups first, or reduce the range of motion using a folded mat under your head.",
    harderVariation: "Perform them freestanding away from the wall, or add a deficit using parallettes.",
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    category: "arms",
    description: "The classic mass-building exercise for the biceps.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a barbell with an underhand grip, hands shoulder-width apart.\n2. Curl the bar up toward your shoulders, keeping your elbows pinned to your sides.\n3. Lower back down under control to full arm extension.",
    easierVariation: "Use lighter weight, an EZ-bar, or dumbbells for a more comfortable wrist position.",
    harderVariation: "Increase the load, add a pause at the top, or slow the lowering phase.",
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell Curl",
    category: "arms",
    description: "A biceps isolation exercise performed with a dumbbell in each hand.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand or sit holding a dumbbell in each hand, arms fully extended, palms facing forward.\n2. Curl one or both dumbbells up toward your shoulders, keeping your elbows still.\n3. Lower back down under control to full extension.",
    easierVariation: "Use lighter dumbbells or alternate arms one at a time.",
    harderVariation: "Increase the weight, or slow the lowering phase significantly.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    category: "arms",
    description: "A curl variation with a neutral grip that also targets the forearms.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand holding a dumbbell in each hand, palms facing each other.\n2. Curl the dumbbells up toward your shoulders while keeping your palms facing in.\n3. Lower back down under control.",
    easierVariation: "Use lighter dumbbells or alternate arms.",
    harderVariation: "Increase the weight, or add a pause at the top of each rep.",
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    category: "arms",
    description: "A curl performed with your arms braced on a preacher bench, isolating the biceps and removing momentum.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Sit at a preacher bench with your upper arms resting flat on the pad, holding a barbell or dumbbells.\n2. Curl the weight up toward your shoulders, keeping your upper arms pressed into the pad.\n3. Lower back down under control to just short of full lockout.",
    easierVariation: "Use lighter weight and stop short of full extension at the bottom.",
    harderVariation: "Increase the load, or add a pause at the top of each rep.",
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown (Cable)",
    category: "arms",
    description: "A cable isolation exercise that targets the triceps.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand facing a cable machine with a bar or rope attached at the top.\n2. Grip the attachment with elbows tucked at your sides.\n3. Push the attachment down until your arms are fully extended, squeezing your triceps.\n4. Let it return under control without letting your elbows drift forward.",
    easierVariation: "Reduce the weight stack and keep your elbows firmly pinned to your sides.",
    harderVariation: "Increase the weight, add a pause at the bottom, or slow the return.",
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    category: "arms",
    description: "A lying triceps extension performed with a barbell or dumbbells.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Lie on a flat bench holding a barbell or dumbbells above your chest, arms extended.\n2. Bend your elbows to lower the weight toward your forehead, keeping your upper arms still.\n3. Extend your arms back up to the starting position.",
    easierVariation: "Use lighter weight and reduce the range of motion.",
    harderVariation: "Increase the load, or slow the lowering phase for extra time under tension.",
  },
  {
    id: "overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    category: "arms",
    description: "A triceps isolation exercise performed with the weight overhead.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand or sit holding a single dumbbell with both hands overhead, arms extended.\n2. Bend your elbows to lower the dumbbell behind your head.\n3. Extend your arms back up to full extension, keeping your elbows pointed forward.",
    easierVariation: "Use a lighter dumbbell and reduce the range of motion.",
    harderVariation: "Increase the weight, or perform it single-arm for extra stability demand.",
  },
  {
    id: "triceps-kickback",
    name: "Triceps Kickback",
    category: "arms",
    description: "An isolation exercise for the triceps performed in a hinged position.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Hinge forward at the hips holding a dumbbell in one hand, upper arm parallel to the floor.\n2. Extend your arm straight back until it's fully extended, squeezing your triceps.\n3. Bend your elbow to return to the starting position, then repeat before switching arms.",
    easierVariation: "Use a lighter dumbbell and reduce the range of motion.",
    harderVariation: "Increase the weight, or add a pause at full extension each rep.",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    category: "core",
    description: "A dynamic core exercise that combines a twist with alternating leg movement.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with hands behind your head, knees bent and lifted.\n2. Bring one elbow toward the opposite knee while extending the other leg out.\n3. Alternate sides in a smooth pedaling motion.",
    easierVariation: "Slow the pace down significantly, or keep the extended leg bent slightly.",
    harderVariation: "Increase the pace, or add a pause at each twisted position.",
  },
  {
    id: "v-up",
    name: "V-Up",
    category: "core",
    description: "A full-range core exercise that folds your body into a V shape.",
    defaultReps: 12,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Lie flat on your back with arms extended overhead and legs straight.\n2. Simultaneously lift your legs and upper body, reaching your hands toward your feet.\n3. Lower back down under control to the starting position.",
    easierVariation: 'Bend your knees as you lift, or alternate lifting one leg at a time (a "tuck-up").',
    harderVariation: "Hold a light weight in your hands, or add a pause at the top of each rep.",
  },
  {
    id: "toe-touches",
    name: "Toe Touches",
    category: "core",
    description: "A simple upper-ab focused crunch reaching for your toes.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with legs extended straight up toward the ceiling.\n2. Reach your hands up toward your toes, lifting your shoulders off the floor.\n3. Lower back down under control.",
    easierVariation: "Bend your knees slightly, or reduce the range of the reach.",
    harderVariation: "Hold a light weight in your hands, or slow the tempo further.",
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    category: "core",
    description: "A stability-focused core exercise performed on all fours.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Start on your hands and knees, hands under shoulders, knees under hips.\n2. Extend one arm forward and the opposite leg back, keeping your hips and back level.\n3. Return to the start and repeat on the other side.",
    easierVariation: "Extend only the arm or only the leg at a time, not both together.",
    harderVariation: "Add a pause at full extension, or add light ankle/wrist weights.",
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "core",
    description: "An anti-rotation core exercise performed with a cable or band.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand sideways to a cable or anchored band at chest height, holding the handle with both hands at your chest.\n2. Press the handle straight out in front of you, resisting the pull rotating your torso.\n3. Bring it back to your chest under control, then complete all reps before switching sides.",
    easierVariation: "Use a lighter resistance and stand closer to the anchor point.",
    harderVariation: "Increase the resistance, or add a pause at full extension each rep.",
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    category: "core",
    description: "A lower-ab focused crunch that lifts the hips off the floor.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Lie on your back with knees bent 90 degrees, shins parallel to the floor.\n2. Curl your hips up off the floor toward your chest, using your lower abs.\n3. Lower back down under control without swinging your legs.",
    easierVariation: "Reduce the range of motion, or keep your feet lightly touching the floor between reps.",
    harderVariation: "Straighten your legs toward the ceiling, or slow the tempo further.",
  },
  {
    id: "burpees",
    name: "Burpees",
    category: "cardio",
    description: "A full-body cardio exercise combining a squat, plank, push-up, and jump.",
    defaultReps: 10,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Start standing, then squat down and place your hands on the floor.\n2. Kick your feet back into a plank position, optionally adding a push-up.\n3. Jump your feet back toward your hands, then explode up into a jump.",
    easierVariation: "Remove the push-up and the jump, stepping back instead of kicking.",
    harderVariation: "Add a push-up and a tuck jump at the top, or increase the pace.",
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    category: "cardio",
    description: "A hip-hinge power exercise that builds cardio conditioning and posterior chain strength.",
    defaultReps: 15,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet shoulder-width apart, holding a kettlebell with both hands in front of you.\n2. Hinge at the hips to swing the kettlebell back between your legs.\n3. Drive your hips forward explosively to swing the kettlebell up to chest height.",
    easierVariation: "Use a lighter kettlebell and focus on the hip hinge pattern first.",
    harderVariation: "Use a heavier kettlebell, or swing to overhead height (American swing).",
  },
  {
    id: "farmers-walk",
    name: "Farmer's Walk",
    category: "cardio",
    description: "A loaded carry exercise that builds grip, core, and full-body conditioning.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Pick up a heavy dumbbell or kettlebell in each hand, standing tall with shoulders back.\n2. Walk forward for the target distance or time, keeping your core braced.\n3. Set the weights down under control at the end.",
    easierVariation: "Use lighter weights or walk for a shorter distance.",
    harderVariation: "Increase the weight, walk further, or carry a single weight on one side for an added core challenge.",
  },
  {
    id: "box-jump",
    name: "Box Jump",
    category: "cardio",
    description: "An explosive plyometric exercise jumping onto an elevated box or platform.",
    defaultReps: 8,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Stand facing a sturdy box, feet shoulder-width apart.\n2. Bend your knees and swing your arms back, then explode up and forward onto the box.\n3. Land softly with both feet, then step back down (don't jump down).",
    easierVariation: "Use a lower box, or step up instead of jumping.",
    harderVariation: "Use a higher box, or add a pause before each jump to remove momentum.",
  },
  {
    id: "sled-push",
    name: "Sled Push",
    category: "cardio",
    description: "A loaded pushing exercise that builds leg power and conditioning.",
    defaultReps: 20,
    defaultSets: 3,
    difficultyTier: 2,
    instructions:
      "1. Load a sled with an appropriate weight and grip the handles at hip or shoulder height.\n2. Drive forward in short, powerful steps, keeping your chest up and core braced.\n3. Push for the target distance, then reset and repeat.",
    easierVariation: "Use lighter weight and push for a shorter distance.",
    harderVariation: "Increase the weight, or push for a longer distance at a faster pace.",
  },
  {
    id: "jump-rope",
    name: "Jump Rope",
    category: "cardio",
    description: "A classic cardio exercise that builds coordination and conditioning.",
    defaultReps: 60,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Hold the rope handles at hip height and swing it over your head and under your feet.\n2. Jump just high enough to clear the rope, landing softly on the balls of your feet.\n3. Keep a steady rhythm for the target time.",
    easierVariation: "Practice without the rope first (just the jumping motion), or go at a slower pace.",
    harderVariation: "Increase the pace, or add double-unders (rope passes twice per jump).",
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine (Cardio)",
    category: "cardio",
    description: "A full-body, low-impact cardio exercise on a rowing ergometer.",
    defaultReps: 60,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Strap your feet in and grip the handle with arms extended, knees bent.\n2. Drive through your legs first, then lean back slightly and pull the handle to your ribs.\n3. Reverse the sequence smoothly to return to the starting position.",
    easierVariation: "Reduce the resistance/damper setting and row at an easy, steady pace.",
    harderVariation: "Increase the resistance, or row at a faster pace for the target time.",
  },
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    category: "cardio",
    description: "A high-intensity conditioning exercise using heavy ropes anchored at one end.",
    defaultReps: 30,
    defaultSets: 3,
    difficultyTier: 1,
    instructions:
      "1. Stand with feet shoulder-width apart, holding one end of the rope in each hand.\n2. Whip the ropes up and down alternately as hard and fast as you can.\n3. Keep your core braced and knees slightly bent throughout the set.",
    easierVariation: "Slow the pace, or shorten the work interval.",
    harderVariation: "Increase the pace, use a double-wave pattern, or add a squat between waves.",
  },
];
